# Generated by Django 2.2.2 on 2019-06-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTrader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RunSQL("INSERT INTO crypto_trader_autotrader VALUES(0, 'trader_test')"),
        migrations.AlterField(
            model_name='tradesession',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.api.AutoTrader', to_field='trader_id'),
        ),
    ]
