# Generated by Django 2.2.2 on 2019-06-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190619_1653'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tradesession',
            constraint=models.CheckConstraint(check=models.Q(('active', False), ('end_amount__isnull', False), ('end_time__isnull', False)), name='active_false_end_notnull'),
        ),
        migrations.AddConstraint(
            model_name='tradesession',
            constraint=models.CheckConstraint(check=models.Q(('active', True), ('end_amount__isnull', True), ('end_time__isnull', True)), name='active_true_end_null'),
        ),
    ]
