# Generated by Django 2.2.2 on 2019-06-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_trader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crypto_trader.Currency', to_field='currency_id'),
        ),
        migrations.CreateModel(
            name='TradeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.CharField(max_length=256)),
                ('start_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_time', models.DateTimeField()),
                ('end_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_time', models.DateTimeField()),
                ('simulation', models.BooleanField()),
                ('active', models.BooleanField()),
                ('creator', models.CharField(max_length=256)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crypto_trader.Currency', to_field='currency_id')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('time', models.DateTimeField()),
                ('notes', models.CharField(max_length=1024)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crypto_trader.TradeSession')),
            ],
        ),
    ]
