# Generated by Django 2.2.2 on 2019-06-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.CharField(max_length=16, unique=True)),
                ('base_currency', models.CharField(max_length=16)),
                ('quote_currency', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='candle',
            name='currency_id',
            field=models.CharField(default='FIXME', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
