# Generated by Django 2.2.2 on 2019-06-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_trader', '0002_auto_20190613_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
