# Generated by Django 2.2.2 on 2019-06-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_trader', '0003_auto_20190614_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='currency_id',
            field=models.CharField(max_length=16),
        ),
    ]
