# Generated by Django 2.2.2 on 2019-06-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_trader', '0004_auto_20190614_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='close',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
